services:
  - type: web
    name: wwgang-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_IDS
        sync: false
      - key: WEBHOOK_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: PROXY_URL
        value: ""
